### ISSUE TITLE
not work with sqlite 

### ISSUE THREAD

**Issue by tablecell** [nullivex/lib-db#1]
```
<?php

require 'lss\db.php';

use \LSS\DB as DB;

$config['db']['driver'] = 'sqlite';
$config['db']['database'] = 'lss';

//\LSS\Config::setDefaults($config);
//unset($config);


Db::_get()->setConfig($config['db'])->connect();

```

Fatal error: Uncaught PDOException: could not find driver in  \LSS\Db.php:69
Stack trace:
#0  \LSS\Db.php(69): PDO->__construct(':dbname=;host=;...', NULL, NULL, Array)
#1  \test.php(18): LSS\Db->connect()

**Comment by nullivex** [comment]
Thank you for the report. I will try this myself and issue a fix if needed.
